import { Vendor } from '@/domain/vendor';

export const demoVendors: Vendor[] = [
  {
    id: 'vnd-001',
    name: 'EventPro Inc',
    email: 'contact@eventpro.com',
    phone: '+1 (555) 123-4567',
    description: 'Leading event management company specializing in corporate conferences and networking events. With over 10 years of experience.',
    logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200',
    rating: 4.8,
    totalEvents: 145,
    verified: true,
    specialties: ['Conferences', 'Networking', 'Corporate Events'],
    location: 'San Francisco, CA',
    joinedDate: '2020-01-15',
  },
  {
    id: 'vnd-002',
    name: 'Marketing Masters',
    email: 'hello@marketingmasters.com',
    phone: '+1 (555) 234-5678',
    description: 'Expert workshop organizers focused on digital marketing and business development training.',
    logo: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=200',
    rating: 4.6,
    totalEvents: 89,
    verified: true,
    specialties: ['Workshops', 'Training', 'Marketing'],
    location: 'New York, NY',
    joinedDate: '2021-03-20',
  },
  {
    id: 'vnd-003',
    name: 'Live Events Co',
    email: 'info@liveevents.com',
    phone: '+1 (555) 345-6789',
    description: 'Premier entertainment and concert production company bringing world-class performances to life.',
    logo: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=200',
    rating: 4.9,
    totalEvents: 203,
    verified: true,
    specialties: ['Concerts', 'Festivals', 'Entertainment'],
    location: 'Los Angeles, CA',
    joinedDate: '2019-06-10',
  },
  {
    id: 'vnd-004',
    name: 'Gourmet Events',
    email: 'contact@gourmetevents.com',
    phone: '+1 (555) 456-7890',
    description: 'Culinary event specialists creating unforgettable food and wine experiences.',
    logo: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=200',
    rating: 4.7,
    totalEvents: 67,
    verified: true,
    specialties: ['Food Festivals', 'Wine Events', 'Culinary'],
    location: 'Napa Valley, CA',
    joinedDate: '2021-09-05',
  },
];
