import { Event, EventCategory } from '@/domain/event';

export const demoCategories: EventCategory[] = [
  { id: '1', name: 'Conferences', icon: '🎤', description: 'Professional conferences and seminars' },
  { id: '2', name: 'Workshops', icon: '🛠️', description: 'Hands-on learning experiences' },
  { id: '3', name: 'Concerts', icon: '🎵', description: 'Live music performances' },
  { id: '4', name: 'Sports', icon: '⚽', description: 'Sporting events and tournaments' },
  { id: '5', name: 'Festivals', icon: '🎉', description: 'Cultural and community festivals' },
  { id: '6', name: 'Networking', icon: '🤝', description: 'Professional networking events' },
];

export const demoEvents: Event[] = [
  {
    id: 'evt-001',
    title: 'Tech Innovation Summit 2025',
    description: 'Join industry leaders for a day of insights into the future of technology. Featuring keynote speakers from top tech companies.',
    category: 'Conferences',
    date: '2025-07-15',
    time: '09:00 AM',
    location: 'San Francisco, CA',
    venue: 'Moscone Center',
    price: 299,
    currency: 'USD',
    capacity: 500,
    availableSeats: 120,
    vendorId: 'vnd-001',
    vendorName: 'EventPro Inc',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    tags: ['Technology', 'Innovation', 'Business'],
    featured: true,
    status: 'upcoming',
  },
  {
    id: 'evt-002',
    title: 'Digital Marketing Masterclass',
    description: 'Learn the latest strategies in digital marketing from industry experts. Includes hands-on workshops and networking sessions.',
    category: 'Workshops',
    date: '2025-07-20',
    time: '10:00 AM',
    location: 'New York, NY',
    venue: 'Manhattan Conference Center',
    price: 149,
    currency: 'USD',
    capacity: 200,
    availableSeats: 85,
    vendorId: 'vnd-002',
    vendorName: 'Marketing Masters',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800',
    tags: ['Marketing', 'Digital', 'Workshop'],
    featured: false,
    status: 'upcoming',
  },
  {
    id: 'evt-003',
    title: 'Summer Music Festival',
    description: 'A spectacular outdoor music festival featuring top artists from around the world. Food, drinks, and great vibes guaranteed!',
    category: 'Concerts',
    date: '2025-08-05',
    time: '04:00 PM',
    location: 'Los Angeles, CA',
    venue: 'Hollywood Bowl',
    price: 89,
    currency: 'USD',
    capacity: 2000,
    availableSeats: 450,
    vendorId: 'vnd-003',
    vendorName: 'Live Events Co',
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
    tags: ['Music', 'Festival', 'Entertainment'],
    featured: true,
    status: 'upcoming',
  },
  {
    id: 'evt-004',
    title: 'Startup Networking Night',
    description: 'Connect with fellow entrepreneurs, investors, and startup enthusiasts. Perfect for building meaningful business relationships.',
    category: 'Networking',
    date: '2025-07-25',
    time: '06:00 PM',
    location: 'Austin, TX',
    venue: 'Capital Factory',
    price: 25,
    currency: 'USD',
    capacity: 150,
    availableSeats: 60,
    vendorId: 'vnd-001',
    vendorName: 'EventPro Inc',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800',
    tags: ['Networking', 'Startup', 'Business'],
    featured: false,
    status: 'upcoming',
  },
  {
    id: 'evt-005',
    title: 'Food & Wine Festival',
    description: 'Experience culinary delights from award-winning chefs paired with premium wines from local vineyards.',
    category: 'Festivals',
    date: '2025-08-12',
    time: '12:00 PM',
    location: 'Napa Valley, CA',
    venue: 'Vineyard Gardens',
    price: 125,
    currency: 'USD',
    capacity: 300,
    availableSeats: 180,
    vendorId: 'vnd-004',
    vendorName: 'Gourmet Events',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    tags: ['Food', 'Wine', 'Festival'],
    featured: true,
    status: 'upcoming',
  },
  {
    id: 'evt-006',
    title: 'AI & Machine Learning Workshop',
    description: 'Dive deep into AI and ML with hands-on coding sessions. Perfect for developers and data scientists.',
    category: 'Workshops',
    date: '2025-07-30',
    time: '09:30 AM',
    location: 'Seattle, WA',
    venue: 'Tech Hub Seattle',
    price: 199,
    currency: 'USD',
    capacity: 100,
    availableSeats: 35,
    vendorId: 'vnd-002',
    vendorName: 'Marketing Masters',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
    tags: ['AI', 'Technology', 'Workshop'],
    featured: false,
    status: 'upcoming',
  },
];
